### ISSUE TITLE
TrHologram Support

### ISSUE THREAD

**Issue by ahdg6** [Rosewood-Development/RoseStacker#16]
TrHologram was rewriten recently,It seems that the support for TrHologram can not work properly.
https://github.com/Arasple/TrHologram
https://github.com/Arasple/TrHologram/blob/master/src/main/kotlin/me/arasple/mc/trhologram/api/TrHologramAPI.kt

**Comment by Esophose** [comment]
Resolved by 81bb75ce24407b8bccdef38be8e160633c8f7af5 and will be in the v1.2.0 update.

Would you mind translating a few messages to Simplified Chinese for me? I don't know if I really trust an online translator for these:
```yaml
gui-stacked-spawner-total-spawns: '&eTotal mobs spawned: &b%amount%'
spawner-advanced-place-no-permission: '&cWarning! &eYou do not have permission to place that type of spawner.'
spawner-advanced-break-no-permission: '&cWarning! &eYou do not have permission to pick up that type of spawner.'
spawner-advanced-break-silktouch-no-permission: '&cWarning! &eYou need to use a silk touch pickaxe to pick up that type of spawner.'
```
